title: TEST
description: TEST
baseurl: ""
url: ""

theme: minima

minima:
  skin: auto
  social_links:
    github: 

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: AI

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
